name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DB_NAME: ${{ secrets.DB_NAME }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    - name: Build Docker Image
      id: docker_build
      run: |
        docker buildx build \
          --build-arg SERVICE_ACCOUNT_JSON="$(echo $SERVICE_ACCOUNT_JSON)" \
          --build-arg SECRET_KEY="$(echo $SECRET_KEY)" \
          --build-arg DB_NAME="$(echo $DB_NAME)" \
          -t spending_analysis .
          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Push Docker Image
      run: |
        docker tag spending_analysis:latest spending_analysis:${{ github.sha }}
        docker push spending_analysis:${{ github.sha }}
      
    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
